### ISSUE TITLE
expected ‘)’ before ‘int’

### ISSUE THREAD

**Issue by lijk8890** [JSchaenzle/c-message-queue#1]
put
QUEUE_DECLARATION(test, int, 256);
in test.h

put
QUEUE_DEFINITION(test, int);
int test.c

and i get "test.h:13: error：expected ‘)’ before ‘int’"

please what's wrong?

**Comment by lijk8890** [comment]
put
#include "queue.h"
in test.h

don't put #include "queue.h"  in test.c

i  solved it

**Comment by JSchaenzle** [comment]
Ah, yes that makes sense
